### ISSUE TITLE
Config?

### ISSUE THREAD

**Issue by SDeeb23** [dojwun/qb-clothing#1]
How do I actually get this working?

**Comment by dojwun** [comment]
the peds should already spawn on for the clothes shop but you will need to use qb-target to interact with them .. it should already be set up

**Comment by SDeeb23** [comment]
for some reason the peds didnt spawn in.

**Comment by dojwun** [comment]
alright i will give it a look, also will make an update in the future to be more user friendly.. i wansnt really planning on uploading this, thats why it isnt finished properly

**Comment by SDeeb23** [comment]
ok thank you

**Comment by SDeeb23** [comment]
![unknown](https://user-images.githubusercontent.com/92552588/144951764-e39504a6-92fb-44bc-a1f5-75fc493a3d3b.png)

I just found out that I receive this error

**Comment by dojwun** [comment]
message me on discord and i can help you </dojwun>#2103

**Comment by dojwun** [comment]
i removed qb-target, its reverted to the old press E but with payment options
